---
title: Studio Tech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
email: 
description: 
baseurl: 
url: https://alexitsios.github.io/site/
twitter: 
github: 
instagram: 
facebook: 
markdown: kramdown
permalink: pretty
paginate: 10
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll/tagging
include:
- _pages
exclude:
- vendor
- Gemfile
- Gemfile.lock
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
