---
title: Studio Tech - Το Retrogaming και η Τεχνολογία στα καλύτερα της!
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 100
language: en-uk
words_per_minute: 200
baseurl: "/site/"
description: Το Retrogaming και η Τεχνολογία στα καλύτερα της!
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://alexitsios.github.io/site/
source_url: https://alexitsios.github.io/site/
CNAME: 
navigation: true
subscribers: true
twitter: tryghost
facebook: groups/studiotech.gr/
disqus: false
disqus_shortname: alexitsios
google_analytics: UA-69281367-1
permalink: "/:title"
plugins_dir:
- _plugins
plugins:
- jekyll-paginate
- jekyll-feed
feed:
  path: feed.xml
safe: false
lsi: false
username: alexitsios
repo: site
branch: master
relative_source: "../site/"
exclude:
- assets/css
- node_modules
- vendor
- ".travis.yml"
- Gemfile
- Gemfile.lock
- GHOST.txt
- gulpfile.js
- LICENSE
- package.json
- Rakefile
- README.md
- script.py
- changelog.md
- "*.Rmd"
- ".git*"
