---
title: Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title_left: Studio
title_right: Tech
description: Ένα μινιμαλιστικό blog γύρω από το retro gaming, τα βιβλία και ότι άλλο
  μου κατέβει
keywords: gaming, greece, minimal, books
url: https://alexitsios.github.io/site
baseurl: ''
cover: ''
google_analytics: UA-XXXXX-XX
twitter_username: ''
comments_enabled: false
disqus_shortname: ''
postshare_enabled: false
permalink: "/:year/:title/"
markdown: kramdown
highlighter: rouge
source: "./"
destination: "./_site"
sass:
  sass_dir: assets/scss
  style: compressed
author:
  name: Alex Itsios
plugins:
- jekyll-sitemap
- bourbon
- jekyll-paginate
navbar:
- slug: about
  title: About
- slug: blog
  title: Blog
exclude:
- gulp
- node_modules
- bower
- bower_components
- config.rb
- src
- Gemfile
- Gemfile.lock
- ".rvmrc"
- ".rbenv-version"
- package.json
- gulpfile.js
- README.md
- Rakefile
- changelog.md
- script
- vendor
- thinkspace.gemspec
theme: jekyll-theme-cayman
