---
title: Ghost
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 100
language: en-uk
words_per_minute: 200
baseurl: "/site/"
description: The professional publishing platform
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://alexitsios.github.io/site/
source_url: https://alexitsios.github.io/site/
CNAME: 
navigation: false
subscribers: true
twitter: tryghost
facebook: ghost
disqus: false
disqus_shortname: jekyller
google_analytics: UA-69281367-1
permalink: "/:title"
plugins_dir:
- _plugins
plugins:
- jekyll-paginate
- jekyll-feed
feed:
  path: feed.xml
safe: false
lsi: false
username: jekyller
repo: jasper2
branch: master
relative_source: "../site/"
destination: "../jasper2-pages/"
exclude:
- assets/css
- node_modules
- vendor
- ".travis.yml"
- Gemfile
- Gemfile.lock
- GHOST.txt
- gulpfile.js
- LICENSE
- package.json
- Rakefile
- README.md
- script.py
- changelog.md
- "*.Rmd"
- ".git*"
